### ISSUE TITLE
Strange layer of support-only material (v0.9.10b)

### ISSUE THREAD

**Issue by AndKe** [alexrj/Slic3r-Manual#12]
for STL, and resulting gcode please see:  http://flyfoto-nord.no/gcodeproblem.zip
There are two versions there, one with no support, and one with printed support.

I inspected the supported version , and it has layer "21", that appears to be support only - (when viewed in pronterface) this makes no sense ?

**Comment by lordofhyphens** [comment]
If this is still an issue, please register issue at http://github.com/alexrj/Slic3r. This is for problems with the Manual only.
