### ISSUE TITLE
Support is printed at 30% of default speed, too fast for first layer.:  Suggestion

### ISSUE THREAD

**Issue by AndKe** [alexrj/Slic3r-Manual#13]
Please consider making an option to print first layer of support as speed of "perimeter".
It's basically the same when it comes to make it stick to the surface.

Yes, I could lower support speed, but for all layers except first, high support speed is just fine.

**Comment by lordofhyphens** [comment]
This is not for the Manual, if it is still an issue (with current 1.3.0-dev), put at http://github.com/alexrj/Slic3r/issues
