### ISSUE TITLE
Slic3r question. I seem to get some gaps in narrow spots.

### ISSUE THREAD

**Issue by mrbi11** [alexrj/Slic3r-Manual#15]
Is this the physical limits of the print head width, or is there a different setting in slic3r that can get these gaps filled in. The part in question needs to be strong in the places shown, the tabs with holes are for a screw, so having a void in the narrowest part of the outside of tab is unfortunate.

Suggestions are welcome

![20131117_152734](https://f.cloud.github.com/assets/5921662/1559452/2e03755c-4fd2-11e3-8863-e809f15a173c.jpg)
![20131117_152722](https://f.cloud.github.com/assets/5921662/1559453/2e03a860-4fd2-11e3-90c0-d5d44f729544.jpg)
![20131117_152726](https://f.cloud.github.com/assets/5921662/1559454/2e03b1a2-4fd2-11e3-89ea-23f0894b4b6f.jpg)
![20131117_152642](https://f.cloud.github.com/assets/5921662/1559455/2e0daad6-4fd2-11e3-8695-702df533d95b.jpg)

**Comment by lordofhyphens** [comment]
This is not the appropriate place. Go to https://github.com/alexrj/Slic3r/issues
