### ISSUE TITLE
1.0.0RC2 Variable layer height (UI: manual problem)

### ISSUE THREAD

**Issue by 358Eki** [alexrj/Slic3r-Manual#19]
With 1.0.0RC2 for MacOs: 
-double clicking the part 3D-view of .stl appear and not what manual says. 

Manual Expert mode/Variable layer height:
"The variable layer height options are available by double clicking on a part name in the Plater window. This will cause a pop-up window to be displayed which contains two tabs...
 "Info" is  seen in main window but no "layer-tab".

I just found all behing "settings" right top corner...

**Comment by lordofhyphens** [comment]
Manual does that in 1.2.9 (and 1.3.0).
