### ISSUE TITLE
Manual refers to non-existant menu entry

### ISSUE THREAD

**Issue by PxT** [alexrj/Slic3r-Manual#28]
In the multi-material section, the manual refers to a "Combine multi-material STL files..." menu option. I couldn't find this in the latest v1.2.9. I figured out the proper procedure, but it would be nice to have the manual updated.

http://manual.slic3r.org/expert-mode/multiple-extruders

**Comment by PxT** [comment]
Poor quality writeup of the proper procedure:
> Load the first part like normal, then select it and choose Settings from the icon bar across the top, then the Load Part button to add additional parts.

**Comment by lordofhyphens** [comment]
Well, we're accepting Pull Requests now. The threshold for contributing usefully is much lower now.
