### ISSUE TITLE
Using network each 5 sec

### ISSUE THREAD

**Issue by Luginets** [alexrj/Slic3r-Manual#30]
I notice that slic3r uses network each 5-7 seconds at about 2Mb/s.
![image](https://cloud.githubusercontent.com/assets/7826853/11337049/ab57983a-91f2-11e5-8a8b-4336f824ce35.png)

**Comment by alexrj** [comment]
???
Slic3r only uses network for version check (every to days, completely anonymous) and OctoPrint upload. Do you have more details? Upstream vs downstream, tool used, amount of data?

**Comment by Luginets** [comment]
Sorry, i already resolve this issue. It's happens because destination file was on network drive.))
