### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by claell** [alexrj/Slic3r-Manual#34]
You might want to add a hint that Slic3r is available in the official Ubuntu repos.

**Comment by claell** [comment]
Why?

**Comment by lordofhyphens** [comment]
1. What distros do isn't our concern (or control, the devs don't maintain the distro builds).
1. The distro version lags and we have AppImage builds now as well.
1. This information does not belong in the Manual, we have a Download page.

**Comment by claell** [comment]
Thanks. Although I don't agree with some points, it seems to be alright that you don't want to list sources with maybe outdated versions.
