### ISSUE TITLE
Adaptive slicing description needed

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r-Manual#43]
The new feature for adaptive slicing by @platsch is useful, but it needs a Manual entry to go with it. 

It can go into the topics/ directory and be referenced from print-settings.md (look at the reorg1 branch).

Most important, I feel, explaining how the graph works (with pictures).

Reference pull request: https://github.com/alexrj/Slic3r/pull/1386

**Comment by platsch** [comment]
FYI: started working on this at https://github.com/platsch/Slic3r-Manual/tree/adaptive-slicing-update. Will PR when finished.
