### ISSUE TITLE
Print only one layer/line

### ISSUE THREAD

**Issue by Magic-Pi** [alexrj/Slic3r-Manual#48]
Hey guys,

I created a coil and I want to create a gcode with Slic3r. The cross-section area is 0.2x0.2mm and the Slicer-Software should create only one line/layer of PLA. My idea was to set the nozzle diameter to 0.2 mm and the layer high, first layer hight to 0.2 mm as well. But Slic3r can't generate a gcode. Does someone know why?

With 0.1 mm for nozzle daiamter and both layer highs the softwarte creates a gcode. But in this case the nozzle would move forward and backwards. I could delete the second (backwards) part of the gcode, but is there a way to generate the right code?

**Comment by lordofhyphens** [comment]
Turn on thin walls. Otherwise Slic3r refuses to slice anything smaller than you can do with a full loop.
